config/routes.rb
Rails.application.routes.draw do
    root to: 'pages#home'
    devise_for :users, controllers: { registrations: 'users/registrations' }
    resources :users do
       resource :profile 
    end
    get 'about', to: 'pages#about'
    resources :contacts, only: :create
    get 'contact-us', to: 'contacts#new', as: "new_contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates:name , presence: true   
    validates:email , presence: true   
    validates:comments , presence: true   

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users  
end

app/models/profile.rb
class Profile < ActiveRecord::Base

belongs_to :user
has_attached_file   :avatar,
                    :styles => { :medium => "300x300>", :thumb => "100x100>"},
                    :default_url => "/images/:style/:missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage/\.*/Z\

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  belongs_to :plan
  has_one :profile
  
  attr_accessor :stripe_card_token
  # If Pro user passes valiations (email passwords etc) than call Stripe and
  # tell Stripe to set up a subscription upon charging a customers card.
  #Stripe responds back with customer data, and we store customer.id as the 
  # customer token, and we save the user.
    def save_with_subscription
      if valid?
        customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
        self.stripe_customer_token = customer.id
        save!
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
      # Whitelist the following form fields so we can process them if coming from a Devise signup form
      before_action :configure_permitted_parameters, if: :devise_controller?
        protected
        def configure_permitted_parameters
         devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:stripe_card_token, :email, :password, :password_confirmation) }
        end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  def create
     @contact = Contact.new(contact_params)
      if @contact.save
        name = params[:contact][:name]
        email = params[:contact][:email]
        body = params[:contact][:comments]
        ContactMailer.contact_email(name, email, body).deliver
        flash[:success] = "Message Sent"
          redirect_to new_contact_path
      else
        flash[:danger] = @contact.errors.full_messages.join(". ")
         redirect_to new_contact_path
      end
  end
  
  private
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @basic_plan = Plan.find(1)
    @pro_plan = Plan.find(2)
  end
  
  def about
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET to /users/:user_id/profile/new
  def new
    # Render blank profile details form
    @profile = Profile.new
  end
  
 # POST to /users/:user_id/profile
def create
  # Ensure that we have the user who is filling out form
  @user = User.find( params[:user_id] )
  # Create profile linked to this specific user
  @profile = @user.build_profile( profile_params )
  if @profile.save
    flash[:success] = "Profile updated!"
    redirect_to redirect_to user_path( params[:user_id] )
  else
    render action: :new
  end
end
private
  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :job_title, :phone_number, :contact_email, :description)
  end
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  
  before_action :select_plan, only: :new
  
  def create
    # Extend default Devise gem so that users signing up with a pro account
    # (plan id 2) save with a special subscription function
    # Otherwise Devise signs up user as usual.
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_subscription
        else
          resource.save
        end
      end
    end
  end
  
  private
  def select_plan
    unless (params[:plan] == '1' || params[:plan] == '2')
      flash[:notice] = "Please select a membership plan to sign up."
      redirect_to root_url
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET to /users/:id
  def show
    @user = User.find( params[:id] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-center">Contact Us.</h3>
       <div class="col-md-6 col-md-offset-3">
         <div class="well">
           <%= form_for @contact do |f| %>
            <div class="form-group">
              <%= f.label:name %>
              <%= f.text_field:name, class: 'form-control' %>
            </div> 
            <div class="form-group">
              <%= f.label:email %>
              <%= f.text_field:email, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label:comments %>
              <%= f.text_area:comments, class: 'form-control' %>
            </div>
              <div class="form-group">
              <%= f.submit 'Submit', class: 'btn btn-default' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frame Rate</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container-fluid nav-line">
        </div>
      <div class='container'>
        
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <%= link_to root_path , class: "navbar-brand" do %>
              <i class="fa fa-film"></i>
              Frame Rate
            <% end %> 
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">
            <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Become A Creator" , '#' %></li>
            <li><%= link_to "About" , about_path %></li>
            <!-- /<li><%= link_to "Contact Us" , new_contact_path %></li> -->
            <!-- /if logged in stuff -->
            <% if user_signed_in? %>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class:""%></li>
              <li><%= link_to "My Profile", new_user_profile_path(user_id: current_user.id)if user_signed_in? %></li>
            <% else %>
             <li><%= link_to "Log In", new_user_session_path, class:""%></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
  </nav>
          <div class="container flash-container">
            <% flash.each do |type, msg| %>
              <%= content_tag :div, msg, class: "alert alert-#{type}" %>
            <% end %>
          </div>
          
      <%= yield %>
      
       <div class="navbar navbar-inverse foot">
          <div class="container-fluid"">
            <ul class="nav navbar-nav navbar-left" style="font-size: 10px;">  
              <li><a href="#">About</a></li>
              <li><a href="#">Terms</a></li>
              <li><a href="#">Privacy</a></li>
            </ul>
          </div>
        </div>

  </body>
</html>

app/views/pages/about.html.erb
<div class="about-callout text-center container-fluid full-image-about">
    <h1>Search, find, and connect with the best.</h1>
    <h3>Find filmmakers, video editors, animators, and more.</h3>
</div>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid full-image-home">
    <h1>Connect with the best in the video & filmmaking industry.</h1>
    <h3>Find filmmakers, video editors, animators, and more.</h3>
</div>

<div class="home-strap text-center container-fluid">
    <h2>Popular Creator Profiles</h2>
    <h4>Check out a few of our most popular creators below.</h4>
    <br>
    <h4><i class="fa fa-chevron-down"></i></h4>
</div>

<div class="container">
    <div class="row">
        <div class="text-center ">
            <img class="col-md-6 home-profile-img" src="https://images.unsplash.com/photo-1431727460781-fa165e66bffa?dpr=2&auto=compress,format&fit=crop&w=500&h=350&q=80"></img>
        </div>
        <div class="col-md-6">
            <div class="text-left home-profile">
                <h2>Brian Radcliffe</h2>
                <h4>Motion Graphics Designer / Atlanta, GA</h4>
                <br>
                <p>Hi, I’m Brian. I design, illustrate and animate videos.
                My work ranges from broadcast television to startup explanatory videos.
                I love to meet people, hear their stories, and bring those stories to life.
                <br><br>
                I have had the pleasure of working with a great number of clients, 
                big and small. Some of those great people include: CNN, HGTV,
                The Weather Channel, TNT, Cartoon Network, DIY, ABC Family, Coca-Cola, 
                Turner Studios and Stone Mountain.</p>
                <br>
                <%= link_to '#', class:"btn b-btn btn-lg" do %>
                    View Profile 
                    <i class="fa fa-arrow-circle-o-right btn-icon"></i>
                <% end %>
            </div>
        </div>
    </div>
</div>

<div class="gray container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="text-left home-profile">
                    <h2>John Waddington</h2>
                    <h4>Videographer / New York, NY</h4>
                    <br>
                    <p>Hi, I’m John. I design, illustrate and animate videos.
                    My work ranges from broadcast television to startup explanatory videos.
                    I love to meet people, hear their stories, and bring those stories to life.
                    <br><br>
                    Some of my clients include: CNN, HGTV,
                    The Weather Channel, TNT, Cartoon Network, DIY, ABC Family, Coca-Cola, 
                    Turner Studios and Stone Mountain.</p>
                    <br>
                    <%= link_to '#', class:"btn b-btn btn-lg" do %>
                        View Profile 
                        <i class="fa fa-arrow-circle-o-right btn-icon"></i>
                    <% end %>
                </div>
            </div>
            <div class="text-center">
                <img class="col-md-6 home-profile-img" src="https://images.unsplash.com/photo-1469078516084-ad19542d5662?dpr=2&auto=format&fit=crop&w=767&h=511&q=80&cs=tinysrgb&crop="></img>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="text-center ">
            <img class="col-md-6 home-profile-img" src="https://images.unsplash.com/photo-1438109491414-7198515b166b?dpr=2&auto=format&fit=crop&w=767&h=511&q=80&cs=tinysrgb&crop="></img>
        </div>
        <div class="col-md-6">
            <div class="text-left home-profile">
                <h2>Jennifer Williams</h2>
                <h4>Video Editor / Los Angeles, CA</h4>
                <br>
                <p>Hi, I’m Jen. I design, illustrate and animate videos.
                My work ranges from broadcast television to startup explanatory videos.
                I love to meet people, hear their stories, and bring those stories to life.
                <br><br>
                I have had the pleasure of working with a great number of clients, 
                big and small. Some of those great people include: CNN, HGTV,
                The Weather Channel, TNT, Cartoon Network, DIY, ABC Family, Coca-Cola, 
                Turner Studios and Stone Mountain.</p>
                <br>
                <%= link_to '#', class:"btn b-btn btn-lg" do %>
                    View Profile 
                    <i class="fa fa-arrow-circle-o-right btn-icon"></i>
                <% end %>
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="well text-center home-signup-links">
                <h2 class="text-center">Basic Membership</h2>
                <h4>Sign up for free and get access to the community and contact information.</h4>
                <br>
                <%= link_to "Sign Up With Basic", new_user_registration_path(plan: @basic_plan.id) , class:"btn btn-primary btn-lg" %>
            </div>
        </div>
        <div class="col-md-6">
            <div class="well text-center home-signup-links">
                <h2>Creator's Account</h2>
                <h4>Sign up for the creator's account for $10/month and get listed in our community</h4>
                <br>
                <%= link_to "Sign Up With Pro", new_user_registration_path(plan: @pro_plan.id) , class:"btn btn-success btn-lg" %>
            </div>
        </div>
    </div>
</div>


<div class="gray container-fluid">
    <div class="client-logos text-center container">
        <div class="row block-center">
            <div class="col-lg-12">
                <h5>We might be used by these great companies one day.</h5>
                <br>
            </div>
            <div class="client-logos-pad">
                <div class="col-lg-2 col-lg-offset-1">
                   <img class="img-responsive" src="https://motionarray.com/assets/images/content/client-logos/client-cbs.png" alt="">
                </div>
                <div class="col-lg-2">
                   <img class="img-responsive" src="https://motionarray.com/assets/images/content/client-logos/client-clear-channel.png" alt="">
                </div>
                <div class="col-lg-2">
                   <img class="img-responsive" src="https://motionarray.com/assets/images/content/client-logos/client-universal.png" alt="">
                </div>
                <div class="col-lg-2">
                   <img class="img-responsive" src="https://motionarray.com/assets/images/content/client-logos/client-cbs.png" alt="">
                </div>
                <div class="col-lg-2">
                   <img class="img-responsive" src="https://motionarray.com/assets/images/content/client-logos/client-ea.png" alt="">
                </div>
            </div>
        </div>
    </div>
</div>

<div class="home-strap text-center container-fluid">
    <h2>What are you waiting for?</h2>
    <h4>Sign up now, and work with the best in the business.</h4>
    <br>
    <btn class="btn ol-btn btn-lg">Sign Up</btn>
    <br>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :job_title %>
    <%= f.select :job_title, ['Video Editor', 'Videographer', 'Motion Graphics Designer', 'VFX Artist', '3D Artist', 'Audio'], {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn g-btn' %>
  </div>
<% end %>

app/views/profiles/new.html.erb
<div class="home-strap home-callout">
    <h1 class="text-center">Create Your Profile</h1>
    <h4 class="text-center">Be a part of the Frame Rate community and fill out your profile!<h4>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.profile.first_name %> <%= @user.profile.last_name %>
<%= @user.profile.job_title %>
<% if current_user.plan_id == 2 %>
  <%= @user.profile.phone_number %>
  <%= @user.profile.contact_email %>
<% end %>
<%= @user.profile.description %>